### ISSUE TITLE
GTK2 and Qt application - to big margin for window resize cursor

### ISSUE THREAD

**Issue by pkomur** [vinceliuice/Abrus-gtk-theme#1]
![zrzut ekranu z 2018-01-19 09-28-27](https://user-images.githubusercontent.com/11897534/35141544-85f8a68a-fcfb-11e7-9a38-11910f5ef519.png)

![zrzut ekranu z 2018-01-19 09-28-02](https://user-images.githubusercontent.com/11897534/35141610-bf7f8e78-fcfb-11e7-8de2-13754aa1d9c1.png)

**Comment by pkomur** [comment]
There are some errors in logs:
![zrzut ekranu z 2018-01-20 08-47-14](https://user-images.githubusercontent.com/11897534/35181258-b6d186c8-fdbe-11e7-96ca-188365f55212.png)

**Comment by vinceliuice** [comment]
I adjusted the size and value of the shadow, You can try the new one

**Comment by pkomur** [comment]
It's better now, but it's still too big compared to GTK3.

**Comment by pkomur** [comment]
After #f80ade3 commit is OK. Thanks.

**Comment by vinceliuice** [comment]
You are welcome, Finally fixed
